# fly.toml app configuration file generated for lively-forest-6097 on 2023-11-11T22:11:17+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lively-forest-6097"
primary_region = "syd"

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
